services:
  discord:
    build: .
    image: iut-tlse3/discord_bot:latest
    container_name: psebot
    network_mode: host
    environment:
      - "TZ=Europe/Paris"
      - "DISCORD_TOKEN=XXX" # Discord bot token
      - NB_VOICE_CHANNELS=5
      - "COMMAND_PREFIX=!"
      - "ROLE_INTERVENANT_PREFIX=→ "
      - "ROLE_INTERVENANT_NAME=Intervenant"
    restart: unless-stopped
